//
//  Day1View.swift
//  BigEvent2020 WatchKit Extension
//
//  Created by Joey deVilla on 2/8/20.
//  Copyright © 2020 Joey deVilla. All rights reserved.
//

import SwiftUI

struct ListItem: Identifiable {
  let id = UUID()
  var time: String
  var name: String
  var details: String
}

struct Day1View: View {

  let gray = Color(red: 0.2, green: 0.2, blue: 0.2)

  var items = [
    ListItem(time: "Day 1\n8:00am - 5:00pm",
             name: "Badge Pickup and On-Site Registration",
             details: "Pick up your name badge for Synapse Summit 2020 at the ReliaQuest Ticket Office. Photo ID required. Show the QR code you receive by email for speedy badge pickup.\n\nAccess the ReliaQuest Ticket Office near Channelside Drive via Thunder Alley, the main plaza at Amalie Arena."),
    ListItem(time: "Day 1\n8:30am - 5:00pm",
             name: "Talent Lounge - Tuesday",
             details: "Connect, relax and plug in any time during the Synapse Summit at the Talent Lounge."),
    ListItem(time: "Day 1\n9:00am - 9:45am",
             name: "Networking Like a Pro - Maximizing Your Summit Experience",
             details: "Sponsored by Synapse\n\n We network every day without even realizing it! But an event like Synapse Summit with 6000+ attendees is a unique opportunity to maximize your opportunities. In this interactive presentation, Nathan A. Perez, author of the multi-award winning The 20-Minute Networking Meeting, will discuss the ground-breaking concepts of structured, brief and reciprocal networking. Refine your interpersonal skills focused on Spontaneous, Social and Speed networking. This skill session will get you shaking hands, conversing with others at the event, and walking away with a simple, but critical skillset that will impact the rest of your event— and career."),
      ListItem(time: "Day 1\n9:00am - 9:45am",
               name: "Cryptocurrency & Digital Assets: The Future of Programmable Money & Payments",
               details: "Sponsored by BlockSpaces\n\nFB Libra, JPM Coin, Twitter's Jack Dorsey investing in CoinList - are the traditional ideas of paper money and checks disappearing? Cryptocurrency and digital assets are meant to increase the security of currency and verify transactions, making the process more secure and convenient. Learn the latest on how crypto is impacting the fintech market and the business implications for the everyday person."),
      ListItem(time: "Day 1\n9:00am - 9:45am",
               name: "Doing Well By Doing Good",
               details: "Sponsored by BlockSpaces\n\nToday's entrepreneurs are about more than just making money. In a culture where customers want to do business with companies that have a mission (not just to grow and make money) but to do good in the universe, social entrepreneurship has become a standard of doing business. Social entrepreneurship is an approach by which companies develop, fund and implement solutions to social, cultural, or environmental issues. If you want to do some good but are not quite sure where to start, join Candice Rezvanian (Director of Founder Success at Florida Funders) as she discusses social entrepreneurship with Jason Sowell (Founder of Current Initiatives), Suhas Apte (President of TiE Tampa Bay), and Tony Selvaggio (eSmart Recycling), and Dr. Kelli Wells (Florida Blue)."),
      ListItem(time: "Day 1\n9:00am - 9:30am",
               name: "Sneak Peek: Take a VR Tour of PwC's New Workplace",
               details: "Sponsored by PwC\n\nSynapse attendees can be among the first to see a sneak peek of PwC's newest office design, which has employee experience at the forefront and is built to enable our New World New Skills mindset. As PwC digitally upskills our people across the country, new and exciting ways of working are taking shape allowing us to keep pace with our rapidly changing business world. Come take a tour!"),
      ListItem(time: "Day 1\n9:30am - 10:00am",
               name: "Pitch Madness - Round 1",
               details: "Sponsored by Synapse\n\nIn a world that preaches disruption, founders have been stuck pitching their startups through the same boring format for way too long. So we set out to develop a better way for entrepreneurs to put their talents on display as visionaries and company builders. Pitch Madness combines the elements of a Head2Head tournament with monitored debate, creating an environment where founders have to think on their feet!"),
      ListItem(time: "Day 1\n9:30am - 10:45am",
              name: "Experience Virtual Reality",
              details: "Sponsored by St. Pete College\n\nVirtual Reality (VR), a simulated computer environment in three dimensions, is becoming more popular for gaming, movies, social interaction, and education. In fact, VR is starting to complement traditional education practices by immersing users into a world where they can learn on a completely new level. In this event: · Learn what VR is and what it is capable of doing while actually being inside VR, · Understand how VR will change everything ranging from medical innovation to education, · Discover various products and tools on the market now and those that are soon to be released, · Experience the potential of Rumii, a “social-virtual reality platform that enables people to educate and collaborate in a 3D virtual environment from anywhere on earth."),
      ListItem(time: "Day 1\n10:00am - 11:00am",
               name: "Emerging Tech Talent Hour",
               details: "Sponsored by IBM\n\nLooking to network, find your next great hire or great place to work? Join us in the Talent Lounge! For professionals in blockchain, AI/ML, digital reality, data science or other “emerging tech” fields."),
      ListItem(time: "Day 1\n10:00am - 10:30am",
               name: "Women in Technology- How to Overcome Objections and Ensure Success",
               details: "Sponsored by PwC\n\nOvercoming objections and how to seize the opportunities that women in technology have today."),
      ListItem(time: "Day 1\n10:00am - 10:45am",
               name: "Everything You Need to Know for a Career in Cybersecurity",
               details: "Sponsored by ReliaQuest\n\nCybersecurity has become the most essential business need for every company and a promising career path for many. ReliaQuest, one of the fastest growing companies in the global cybersecurity industry, fortifies some of the world's leading brands against cyber threats. They have developed a unique partnership with USF to train and empower the next generation of technologists ready to lead."),
      ListItem(time: "Day 1\n10:00am - 10:45am",
               name: "Sales Development 101",
               details: "Sponsored by Synapse\n\nEvery successful company that’s gone IPO, had a merger/acquisition or experienced explosive growth, has mastered the art of sales development, have you? Many companies have a marketing plan and can find sales people that know how to sell, but there’s an art to expanding into new markets and territories. QM’s leadership has developed over $1B in sales pipeline and has contributed over $300M in closed-won sales opportunities for IT software, services and innovative organizations looking to scale their customer base. In our discussion, we will talk about the importance of sales development, building your team, what tools are right for you, how to build your outbound sales cadence, define your sales qualification criteria and establish quotas that align to your ROI goals."),
      ListItem(time: "Day 1\n10:00am - 10:45am",
               name: "A Corporate Take on Healthcare Innovation",
               details: "Sponsored by Tampa General Hospital\n\nPayers and Providers take the Synapse main stage to talk Healthcare Innovation. Learn how some of Florida's largest healthcare institutions are leveraging cutting edge technologies to provide better care for patients across the continuum of care."),
      ListItem(time: "Day 1\n10:00am - 10:45am",
               name: "Hiring Our Heroes: Attracting and Retaining Senior Military Leaders in Business",
               details: "Sponsored by Synapse\n\nVeterans are some of the workforce's most agile, creative, mission-driven and effective business leaders. This untapped talent pool can transform your business, if they have the chance. Learn how - and why - to connect this incredible talent pipeline to your business."),
      ListItem(time: "Day 1\n10:00am - 10:45am",
               name: "Aging Gracefully: Innovations Improving Life for Millions of Seniors",
               details: "Sponsored by USF\n\nBy 2030, all baby boomers will be older than age 65. In 2020, Floridians over the age of 60 are more than 25% of Florida's population. This will expand the size of the older population so that 1 in every 5 residents will be retirement age. Innovation can ensure that their health and quality of life are maintained and sustained, even as their needs increase. Local researchers are creating revolutionary technology, in coordination with The Villages, a community of more than 115,000 residents age 55+. Find out how Florida is leading the way ensuring all of us will be able to age gracefully."),
      ListItem(time: "Day 1\n10:00am - 10:45am",
               name: "Innovation Lives in … Finance? Yes, Finance! 7 Innovation Tips for Driving Financial Success",
               details: "Sponsored by CFO Alliance\n\nJoin this session to hear real stories about entrepreneurs who are stretching innovation to their finance function to accelerate growth. From fundraising, to cash flow, forecasting and beyond - learn about accessible tools you can use to drive growth and profitability in your business."),
      ListItem(time: "Day 1\n10:00am - 11:30am",
               name: "Think with Your Hands: An Adventure in LEGO® Serious Play®",
               details: "Sponsored by The Dali Museum\n\nHave your meetings or planning sessions ever suffered from any of the following? Groupthink? Lack of focus? Low engagement? If so, engaging in some hard fun with LEGO® Serious Play® will jumpstart some ideas for doing things differently by combining the power of visual images with the art of storytelling. This 3D process helps surface information and insights, develops deeper knowledge, and identifies solutions faster—with 100% engagement. In this session, we will focus on the power and potential of visual representation, using our 3-D LEGO models to tell rich stories and model better, more effective workplace (or anyplace!) communication principles."),
      ListItem(time: "Day 1\n10:00am - 11:30am",
               name: "Tampa Bay Wave Demo Day",
               details: "Sponsored by Tampa Bay Wave\n\nOur past experiences hosting Demo Day at Synapse have been standing room only and we are excited to welcome investors across the country again. Nine Companies will give short pitches less than 3 minutes each with an opportunity to meet the founders afterwards. From a company re-engineering the modern bra, to a fintech company that recently launched a successful pilot at a national hotel chain, to a 3D printed cast company, this cohort brings a group of visionary founders with a common purpose of transforming their industries. This cohort also features 2 National Startup of the Year Finalists and one company recently accepted into TechStars. The Tampa Bay Wave is proud to be the only Florida based accelerator accepted into the Global Accelerator Network. Presenting Companies include: ECover Global, Exiom, Fruutful, Medzoomer, Nickelytics, OmPay, Rentit, Reptrics, and SoleVenture."),
      ListItem(time: "Day 1\n10:00am - 4:00pm",
               name: "VIP Loft - Tuesday",
               details: "VIPs can connect and enjoy complimentary refreshments in this exclusive loft located in the RSM Loft on the 4th floor."),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "The Greatest Threats to Cybersecurity: Expert Insights into Protecting the World's Most Critical Infrastructures",
               details: "Sponsored by: OPSWAT\n\nJoin two leading cybersecurity experts whose companies successfully protect our country's most critical assets -- from US nuclear facilities to enterprises including Coca-Cola, Southwest Airlines and American Express. ReliaQuest is headquartered in Tampa Bay and expanding rapidly in market and around the globe. Their GreyMatter platform eliminates gaps in security models by connecting existing technology, people, and processes to deliver actionable insights and enable automated response. San Francisco-based OPSWAT recently acquired a Tampa based NAC and SDP company to extend their “Trust No File and Trust No Device” philosophy to trust no network. OPSWAT is a global organization with 9 offices, including Vietnam, Hungary, Romania and Israel. These two cybersecurity leaders will share their insights on current threats and key trends you'll be glad you knew about in the year ahead."),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "New World New Skills: Reshaping the Workforce of the Future",
               details: "Sponsored by PwC\n\nPwC has committed to invest $3B to digitally upskill our Global workforce of 276k employees. We’ll share key focus areas for digital upskilling and thought leadership on how to position your organization to proactively get ahead of the rest. Come see how we are creating the workforce of the future!"),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "Future Thinking: The 21st Century Operating System",
               details: "Sponsored by: Stonehill\n\nIn this volatile and complex global environment, we need active change agents that are empowered to continually create the future right now. There is an entire field, Strategic Foresight, that provides rich context to mapping the future grounded in today’s hard trends and shifting values. Foresight efforts are most successful when they become the “operating system” of an organization, building the capacity in as many people as possible. Learn why a futurist mindset is critical in this new era, and hear practical foresight examples from across industries."),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "Building Your E-commerce and Tech Business for the Ultimate Value Transaction",
               details: "Sponsored by ConnectWise\n\nThe panel will discuss how to optimize value of your e-commerce or tech business. This will be a fireside chat with Shelley Walk with two tech and e-commerce veterans, Arlin Sorenson, a serial entrepreneur (HTG- which was acquired by Connectwise), Sorenson Family Farms, HTS Ag) and Jason Guerrattaz, a serial entrepreneur (United Commerce Group, Valley Biggs, and Website Closers). Both have been entrepreneurs in the tech and e-commerce space, worked in or with large organizations and have built, sold and now advise others on building and selling their businesses. Expect to learn about the planning for, preparation, process and transition of your business to buyers and investors."),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "Humanizing Virtual Reality",
               details: "Sponsored by University of Central Florida\n\nExplore the groundbreaking applications of virtual reality used to navigate the highs and lows of the human experience, from kinesthetic learning to post-traumatic healing. Please note: attendees will be exposed to sights and sounds, including sensory elements from military and war-time scenarios, that may be triggering and/or disturbing for some. Ample warning will be given during the presentation to accommodate attendees’ needs."),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "Prep Your Pitch Workshop",
               details: "Sponsored by Decksmarter\n\nPrep Your Pitch- Are you currently raising capital? Do you intend to do so in the near future? Come learn about the best practices and important tips all founders should know. In this 1 hour session, you will hear about the successful techniques and useful items to remember whether you are pitching to institutional investors or your neighbor next door."),
      ListItem(time: "Day 1\n11:00am - 11:45am",
               name: "Talent Attraction in a Hot Market",
               details: "Sponsored by AppleOne + CEO Nexus\n\nWith unemployment at a low of 3.8 percent, there is a war for talent. Are you asking the question – how do I attract, grow, and retain the best talent in this market? As part of its commitment to talent development for Second Stage Growth companies, Synapse, AppleOne, and CEO Nexus invites you to hear from the Orlando and Tampa Regional leader of AppleOne Employment Services Nicole McMurray, and Steve Quello President of CEO Nexus. Attendees will get an insider’s guide to the importance of structured personnel onboarding and engagement as well as how interns can produce a return on investment. You will leave with tools you can immediately implement that will make an impact on your bottom line. What is your talent story? Does everyone on your team have the same narrative? What are we missing? Come join us and we will begin to solve this together. We are passionate about helping companies build their story. At the end of the day that it is all about people so let’s help you excel in engaging, retaining, and leading their very best."),
      ListItem(time: "Day 1\n11:00am - 1:30pm",
               name: "Lunch - Tuesday",
               details: "Enjoy your lunch while listening to the capitvating keynote presentations! Take a seat in Sections 123 or 124 on Level 3 to get a front row seat at the mainstage.\n\nGeneral Attendees:\nPlease take advantage of the open design kitchens to purchase lunch. Vegetarian options available.\nEasy Sliders or Steak Station at Section 122 on Level 3\nHavana Nights or Dog Gone-it at Section 109 on Level 3\n\nSponsors, Exhibitors and VIPs\nPickup your complimentary lunch at one of these stations:\nFirestick Grill (near Section 201) on Level 4 or\nTalent Hub on Level 1\n\nCatered lunches are provided by Inside the Box catering, a social enterprise of Metropolitan Ministries. Inside the Box Catering serves delicious food and provides culinary arts education and hands-on vocational training to men and women transitioning out of homelessness."),
      ListItem(time: "Day 1\n12:00pm - 1:30pm",
               name: "Keynote Presentations featuring Dr. Steve Currall, President of USF and Jeff Hoffman, Global Entrepreneur from Priceline and uBid.com",
               details: "Sponsored by Synapse\n\nSeating Accessible from Sections 123 + 124 on the Promenade Level Innovation Lives Here!"),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "Latin America + Florida's Booming Business Connections",
               details: "Sponsored by OmniPublic Media\n\nLatin owned businesses are growing in number and importance to the American economy. Contributing more than $700 billion in sales to the economy annually, they are also an important source of employment as sole proprietors and as firms with employees on payroll. One in four new businesses, traditionally key sources of new jobs, is now Latino-owned. Quite simply, small business growth is tied to the fortunes of Latino-owned businesses. This panel will explore how Latin entrepreneurs are not just shaping the Florida economy, but forging new business connections around the globe."),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "Secrets to Success: Insights from Enterprise and Startup",
               details: "Sponsored by: ConnectWise\n\nCustomers are the basis of success. No matter what size of your business or what state of growth it is at, it’s important to know what strategies to use to maximize customer success. We will discuss these strategies and opportunities through different angles, to fit a variety of business situations. Learn the best ways to gain customer success here!"),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "Unpacking the Promise of 5G for Florida",
               details: "Sponsored by: Bay4 Energy\n\nThe fifth generation of cellular service called 5G is around the corner with the promise of changing how consumers use phones and receive connected home services, like streaming video and fast Wi-Fi. By the end of 2025, there will be 2.6 billion 5G subscriptions, according to the Ericsson Mobility Report. With speeds that could be up to 100 times faster than 4G, 5G would allow the download of a movie in seconds and provide vehicles on the road with the ability to communicate with each other in real time. Find out what benefits and costs Florida businesses can realistically expect from 5G and how to prepare with a practical timeframe."),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "Florida Setting the Bar in Blockchain",
               details: "Sponsored by BlockSpaces\n\nInterest in blockchain technology is growing fast in the business world -- and academia and legislators are responding. On May 23, 2019, Florida joined several other trail blazing states as Gov. Ron DeSantis signed SB 1024 (Florida Blockchain Bill) into law to establish the Florida Blockchain Task Force (Blockchain Task Force) within the Florida Department of Financial Services. The goal of the task force is to provide feedback to the governor about how to create and support a Florida blockchain workforce through academic and project based initiatives. This session will give an overview of the findings of the Task Force to date and the current academic involvement in the state as Florida positions to be in an elite group of national leaders as a state that remains open and friendly to innovative companies."),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "VIP Exclusive: Meet and Greet with Jeff Hoffman",
               details: "Sponsored by Synapse\n\nVIP pass holders are invited to meet keynote speaker Jeff Hoffman."),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "Tech Shakeup: How Technology is Shifting the Landscape of Professional Services",
               details: "Sponsored by Hunter Business Law\n\nMore than ever before, professional service providers (e.g. legal, finance, healthcare, insurance) are seeing their practices shift in response to technology. Join us to explore how professionals can learn to leverage technology to maintain their competitive edge and how technology providers can offer their solutions to professionals in a manner that facilitates broader adoption. How is technology enabling professionals to be part of the “GIG economy” and what dramatic changes may this bring? How can technology provide efficiencies to the delivery of professional services, resulting in higher profits, greater client satisfaction and mitigated risk of malpractice? What are the implications of failing to embrace technology to stay innovative? How can technology companies help professionals understand and evaluate the different technology solutions available today - and find the time to implement them? How can the use of modern technology attract talent to your professional firm? How can you create a culture of professionals who embrace technology rather than resist it?"),
      ListItem(time: "Day 1\n2:00pm - 2:45pm",
               name: "“Ripe” for Innovation: How Technology Can Grow Florida's $104 Billion Agriculture Industry",
               details: "Sponsored by: Elevate Inc.\n\nAgriculture in Florida employs 2 million people and contributes more than $104 billion to the state's economy, and nearly $1 trillion in the United States. Florida supplies 40% of the world's orange juice supply and 80% of the fresh vegetables consumed in the US in the winter months. This industry must keep innovating to meet the challenges of a growing population, labor shortages and impacts of climate change. Florida's agriculture industry is “ripe” for investment and innovation. Commissioner of Agriculture Nikki Fried and serial founder and experienced AgTech investor Candice Rezvanian will speak about the opportunities and challenges with entrepreneur Aakash Patel moderating."),
      ListItem(time: "Day 1\n2:00pm - 3:00pm",
               name: "Health + Wellness Talent Hour",
               details: "Sponsored by Florida Blue\n\nFor professionals in health and wellness."),
      ListItem(time: "Day 1\n2:00pm - 2:30pm",
               name: "Our Technology: Reshaping How We Work",
               details: "Sponsored by PwC\n\nAs PwC continues to push boundaries, get a first hand view of how we use technology to simplify lives and drive Digital Upskilling."),
      ListItem(time: "Day 1\n2:00pm - 2:30pm",
               name: "Tampa Bay Innovation Center Company Demos",
               details: "Sponsored by Tampa Bay Innovation Center\n\nIncluding: Expedite Legal, Verapy, Ehrenberg Industries, ENortaryLog, Bulk Nano, GIVVN"),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "How to Catch and Ride the Wave of FinTech Investment",
               details: "Sponsored by Synapse\n\nThe business world continues to evolve, thanks to modern technology. One of the most talked-about tech phenomena today is financial technology, or FinTech. This is the use of modern technology, whether it's software or another form of tech, to design and deliver financial services. In this special session led by The Mandalay Group, our panel of experts will take a closer look at FinTech and why so many people think it's a smart investment opportunity."),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "Vet-Preneurs: Investing in and Supporting Veterans Building Businesses",
               details: "Sponsored by Hillsborough County EDi2\n\nVeterans have a unique skills set honed through years of leadership and project management and execution. There is a wealth of resources available for innovative veterans ready to start their own business. This session will focus on the resources veterans and military spouses can use to start or scale their own venture."),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "Founders Only: Workshop with Jeff Hoffman",
               details: "Sponsored by Synapse\n\nExclusive founders workshop with keynote speaker, global leader and serial entrepreneur Jeff Hoffman. If you are a Founder, please join us!"),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "Venture, Growth + Debt Capital? A Guide to Successfully Capitalize Your Startup",
               details: "Sponsored by SVB Financial Group\n\nPlease join us for a special panel brought to you by Synapse and the Tampa Bay Wave, featuring Updata Partners and Noro-Moseley Partners (National technology investors), Silicon Valley Bank (Global Innovation Bank) and Morris Manning & Martin (Leading Southeast Technology Law Firm). Key topics covered will include: Why Florida technology ecosystem? What do capital providers look for in a technology startup? How to prepare for a successful fundraise? How to optimize capital structure for your startup?"),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "Building Your Brand From the Ground Up: A Marketing Q + A",
               details: "Sponsored by Urban Buffalo Marketing\n\nSo, you’re ready to launch your new startup or creative endeavor, but unsure of where to start when it comes to marketing? Maybe you already have a business, but you’re ready to take your brand to the next level? Building your brand into a respected and recognizable name in your industry may seem like an elusive goal, but with the right tools, guidance, and foundation, you can be well on your way to doing just that! Join our panel for an informal Q+A session where you can ask any of the branding and marketing questions you might have and walk away ready to take the next step in your successful entrepreneurial journey. The experts leading this session include: Daniel Cura, Founder & President of Tidal Marketing; Wes Lehman, Founder of Urban Buffalo Marketing; and Tyana Daley, Communications Manager at Embarc Collective; with our moderator Gabe Lopez, Founder & CEO of Brave People & Brave Haus. In addition to their other clients’ success, Wes and Daniel lead the Synapse marketing team, whose combined efforts have earned Synapse state and countrywide recognition, and positioned Synapse Summit as a nationally trending event. Tyana’s work fostering Tampa Bay’s growing tech community has helped entrepreneurs build thriving businesses in the area. Gabe’s creative work with startups and Fortune 500 companies provides him with a breadth of knowledge for anyone at any stage in their pursuits. The combined experience of this panel will guide you to building a brand that stands out and above the rest!"),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "Building a HealthTech Startup",
               details: "Sponsored by Florida Blue\n\nWant to learn what it takes to get a healthtech startup off the ground? Listen to founders from throughout the State of Florida as they share their successes, trials, and tribulations in a roundtable discussion."),
      ListItem(time: "Day 1\n3:00pm - 3:45pm",
               name: "Our Real Estate: Re-Designing the Way We Innovate",
               details: "Sponsored by PwC\n\nPwC is reimagining the way our technologists work and the space they work in. PwC has made a large investment in designing an incredibly unique space that enables technologists to work in a collaborative and innovative office space. We will explain the process in which the space was designed, the concept behind the design, and unveil captures of the latest renderings of the new space in Tampa."),
      ListItem(time: "Day 1\n3:30pm - 4:30pm",
               name: "Cybersecurity Talent Hour",
               details: "Sponsored by ConnectWise\n\nLooking to network, find your next great hire or great place to work? Join us in the Talent Lounge! For professionals in the cybersecurity field."),
      ListItem(time: "Day 1\n3:30pm - 4:00pm",
               name: "Funny Fails and Spectacular Successes with College H.U.N.K.S. Founders Nick Freidman and Omar Soliman",
               details: "Sponsored by College Hunks Hauling Junk\n\nThere is a beginning to every story, and no business can begin without that first step. Many of the first steps for the HUNKS included taking risks, in fact the whole endeavor was. Astonishingly, most of those gambles have paid off tremendously, but sometimes their effort to “think outside of the box” fell comically flat. Come hear Co-Founders Nick Friedman and Omar Soliman laugh through some of the funny fails and spectacular successes that have launched their pioneer company from two college hunks hauling junk in 2005 into realizing their vision of becoming an iconic brand in the service industry with 150 franchises and $100 million in annual sales. Their newest venture, Trash Butler, a Florida Funders backed company is taking a different path but is sure to bring the great work culture and philanthropic spirit known to these two co-founders and friends."),
      ListItem(time: "Day 1\n4:00pm - 4:45pm",
               name: "VIP Exclusive: From the Battlefield to the Boardroom",
               details: "Sponsored by Synapse\n\nEntrepreneurship from the Trenches- Myths, Facts, and Perspectives is changing the narrative for Veterans and non-Veterans! Join VetToCEO Executive Director Rob Campbell, former Army Colonel turned author, speaker and entrepreneur in the “trenches” of entrepreneurship. Rob will compare his wartime experience to the journey of entrepreneurship. He’ll expose its hard truths, examine those to choose this path and convince us to jump in the trench!"),
      ListItem(time: "Day 1\n4:00pm - 4:45pm",
               name: "Why Every Entrepreneur Needs to Be Thinking about IP!",
               details: "Sponsored by Stanton IP Law\n\nIntellectual Property is a mysterious term that every business owner hears but often struggles with what it really means for their business. Patents and trademarks are the lifeline of your business whether you know it or not. Understanding how to monetize your IP or defend against your competition's IP can be the difference between staying in business or getting a key investment, and going out of business or becoming irrelevant. Join us for a panel discussion about how to stay relevant with your IP!"),
      ListItem(time: "Day 1\n4:00pm - 4:45pm",
               name: "The New Mobility: Florida’s Road to the Future of Transportation",
               details: "Sponsored by Florida Polytechnic University\n\nSelf-driving cars, robotic delivery vessels, personal air vehicles: transportation solutions in search of a market or the realistic future facing Florida? Automakers and tech companies are pushing ahead to develop autonomous vehicles of all types, and when they’re ready, self-driving vehicles will be welcomed on Florida roads, based on a bill signed by Florida Gov. Ron DeSantis allowing for self-driving vehicles without a human operator, one of only a few states in the nation with such a law. To test its LiDAR (light detection and ranging) technology, radar and cameras, Alphabet’s Waymo selected Miami roads to put its cars to the test during the rainy season. While the roads of Florida may be getting ready, the people may not be. Find out the steps Florida needs to take to manage the changing nature of transportation."),
      ListItem(time: "Day 1\n4:00pm - 4:45pm",
               name: "Positioning Your Company for a Capital Raise",
               details: "Sponsored by Morgan Hill Partners\n\nMorgan Hill, an Operators-as-Service firm designed for family offices and PE firms with growth stage investments, will moderate a discussion with companies who have gone through the process for raising capital. It will include advice on things you should look for during the process and how to avoid the pitfalls. The panel will also include a capital company and what they look for in a company."),
      ListItem(time: "Day 1\n4:00pm - 4:45pm",
               name: "Harnessing the Power of Influencer Marketing",
               details: "Sponsored by USF\n\nMillennials are unlike any generation that has preceded them. One of the most popular methods of marketing that resonates with millennials is influencer marketing. In a world of social media, millennials are able to interact and follow each other across multiple platforms. This session is here to help teach corporate leaders about the benefits of influencer marketing and how to market to millennials. It’s time to crack the code that will help corporate leaders learn the best ways to use their branding and marketing in a way that millennials will appreciate."),
      ListItem(time: "Day 1\n4:00pm - 4:45pm",
               name: "Blockchain and Business ROI",
               details: "Sponsored by IBM\n\nWhile many business leaders are still not fully confident in their understanding of blockchain, forward thinking decision-makers are launching PoC’s and pilots utilizing the technology that are showing promise of significant ROI. This session will address some of the most common misbeliefs and traps that C-Suite executives need to disregard when considering blockchain for their respective businesses while highlighting some real world business use cases currently in production."),
      ListItem(time: "Day 1\n4:00pm - 4:30pm",
               name: "Future of Automation",
               details: "Sponsored by PwC\n\nPwC is reimagining the way automation is delivered at scale. By combining capabilities to automate opportunity identification, aggregate those opportunities to auto-create process documentation and PBIs, and finally, leveraging an AI driven reasoning engine to monitor, maintain, and self heal automations with level one IT support tickets. PwC is delivering value with Intelligent Automation with scale@speed."),
      ListItem(time: "Day 1\n4:00pm - 5:00pm",
               name: "CEO Social: “Lonely At the Top” Executive Leadership Reception",
               details: "Sponsored by Apple One and CEO Nexus\n\nThis special event is designed specifically for CEOs and owner operators leading second-stage growth companies ($1M to $30 M, 10 to 100+ employees)."),
      ListItem(time: "Day 1\n4:30pm - 5:00pm",
               name: "Young Tech Leader Social",
               details: "Sponsored by: Emerging Technology Leaders of Tampa Bay\n\nCome join us on our first event of the year for a social to connect with other interns, students, emerging technologists and emerging tech leaders. The Emerging Technology Leaders of Tampa Bay is about developing interns, students, emerging technologists into emerging technology leaders by connecting them with other emerging and established technology leaders. We are hosting Roundtable with technology executives every quarter and Second Annual Summer Interns & Student mixer during the summer."),
      ListItem(time: "Day 1\n4:30pm - 5:00pm",
               name: "USF Connect Company Presentations",
               details: "Sponsored by USF\n\nUSF CONNECT is a business and economic development initiative of the University of South Florida (USF) that provides support for companies including technology and life science start-ups by facilitating access to top-tier research, programming, faculty, students, supporting organizations and funding sources. Meet some of this year's star companies: SyGlass, Protean and Molekule"),
      ListItem(time: "Day 1\n5:30pm - 8:00pm",
               name: "Synapse Social- Day 1 After-Party",
               details: "Sponsored by ConnectWise\n\nHang out and play at Water Street's latest venue: Parks & Rec, just a short walk from Amalie Arena. This adult playground is stocked full of nostalgic arcade games! Hit up Pac Man, NBA Jam, Skeeball, pinball, air hockey, & more. If you’re feeling competitive, sign up for giant beer pong, or take a shot at other outdoor games. We have cornhole, giant jenga, billiards & giant Connect 4. http://parkrecdtsp.com/"),
      ListItem(time: "Day 1\n5:30pm - 8:00pm",
               name: "NASA iTech Presents: Ignite the Night",
               details: "Sponsored by Synapse\n\nMeet entrepreneurs developing technologies addressing a real-world problem that might also be a potential solution for some of NASA's challenges! Synapse is proud to host Ignite the Night, a NASA iTech event, where the top presenter earns a position as one of the 25 semifinalists for the current NASA iTech cycle. This placement ensures evaluation of the technology by NASA's Center Chief technologists and ahead of the final 2020 Cycle I Forum. For more information visit www.nasaitech.org Focus areas include: - Artificial Intelligence and Machine Learning - Biotechnology - System Autonomy - Advanced Manufacturing - X-Factor Innovations"),
      ListItem(time: "Day 1\n5:30pm - 6:30pm",
               name: "Tour USF Health Morsani College of Medicine",
               details: "Space is limited; RSVP at https://camls-us.org/synapse/\n\nThe USF Health Morsani College of Medicine, Taneja College of Pharmacy, and Heart Institute has brought approximately 1,800 students, faculty and researchers to the downtown Tampa waterfront to transform health education and pioneer discoveries to end heart disease. The state-of-the-art building was designed to support small group active learning and a “bench-to-bedside” research dynamic. The numerous collaboration spaces, highly configurable furnishings, and innovative technology tools comprise a showcase space that offers greater flexibility for teaching, studying, testing, experimenting, and interactive learning. The Morsani College of Medicine tour on February 11, 2020, from 5:30 – 6:30 pm, will highlight the following spaces: Auditorium & Vesely Lobby This auditorium space can accommodate up to 400 people for conferences, events, collaborative learning, high-stakes testing and more. The lobby area outside of the auditorium offers a pre-function space with potential for a variety of setups, including catering. Florida Blue Health Knowledge Exchange This state-of-the-art medical library is designed to be technology and collaboration-centric to support the health education and research needs of students and faculty. It features a large-scale video visualization wall for multimedia presentations, executive style reading room, public access computers, IT help desk and a technology showcase conference room for instruction and demonstrations. Experiential Learning Lab This space was designed for flexibility in meeting a variety of different academic needs and purposes. It is primarily used to support medical simulation education and encourages a participatory and collaborative learning style where students are actively engaged in hands-on activities. Space on the tour will be limited to 20 people. To RSVP please visit this website: https://camls-us.org/synapse/ If you have any tour related questions, please email Nicole Lasnicki at nlasnicki@usf.edu."),
  ]

  var body: some View {
    List {
      ForEach(items.indices) { index in
        NavigationLink(destination: DetailView(item: self.items[index])) {
          VStack(alignment: .leading) {
            Text(self.items[index].time).foregroundColor(.blue)
            Text(self.items[index].name).fontWeight(.bold)
          }.padding(10)
        }.listRowBackground((index  % 2 == 0) ? Color(.black) : self.gray)
      }
    }
  }

}
