//
//  Day2View.swift
//  BigEvent2020 WatchKit Extension
//
//  Created by Joey deVilla on 2/8/20.
//  Copyright © 2020 Joey deVilla. All rights reserved.
//

import SwiftUI

struct Day2View: View {

  let gray = Color(red: 0.2, green: 0.2, blue: 0.2)

  var items = [
    ListItem(time: "Day 2\n8:00am - 5:00pm",
             name: "Badge Pickup and On-Site Registration - Day 2",
             details: "Pick up your name badge for Synapse Summit 2020 at the ReliaQuest Ticket Office. Photo ID required. Show the QR code you receive by email for speedy badge pickup.\n\nAccess the ReliaQuest Ticket Office near Channelside Drive via Thunder Alley, the main plaza at Amalie Arena."),
    ListItem(time: "Day 2\n8:30am - 5:00pm",
             name: "Talent Lounge - Wednesday",
             details: "Connect, relax and plug in any time during the Synapse Summit at the Talent Lounge."),
    ListItem(time: "Day 2\n8:30am - 12:00pm",
             name: "Workshop Add-On: Futures Intelligence: Mapping Tomorrow's Disruptors Today",
             details: "Workshop Hosted by Kedge - Email kedge@synapsefl.com for more information or to register\n\nHow do you propel your foresight efforts beyond trend spotting, and move teams to identify emerging disruptors and transformations? In the Futures Intelligence program you will hear about our latest research around culture, technology, governance, economies, sustainability and more. You will then experience a suite of tools that bridge the gap between our fascination with trends and the real work of foresight. We live in an age where accelerating complexity and exponential change is the norm - an unpredictable world that requires a completely different approach to business, economics, technology, analytics, and social development. The growing fluidity of the global economy, the dramatic disruptions of the digital revolution, and the radical empowerment of individuals through mobile computing and micro-manufacturing have combined to create a challenging future landscape. Competitive intelligence benchmarks against today's competitors while business intelligence analyzes data for linear and short-term organizational application. Both activities are necessary, but they fall short of creating market-leading innovation and long-term opportunity development. Futures thinking turns a complex and unclear world into a map of new innovation, possibilities and opportunities - providing revenue-generating futures intelligence, today. 3 key-takeaways: • Learn how futures thinking is the instrument to building resilient, adaptive and transformative strategies. • Gain the skills needed to identify and capitalize on emerging trends, weak signals, and changing patterns while receiving tangible models that will allow participants to apply learnings immediately. • Expand the field of vision around the possibilities of the future so that participants can make better maps and decisions in the present."),
    ListItem(time: "Day 2\n9:00am - 9:45am",
             name: "SEO + Analytics Power Hour",
             details: "Sponsored by: Synapse\n\nOne of the most important factors for any business is discoverability. If your audience can’t find you, you won’t succeed. This session runs you through the necessary tools of SEO and Analytics that will help you reach your target market and gain brand recognition."),
    ListItem(time: "Day 2\n9:00am - 9:45am",
             name: "Transforming your Business with AWS Artificial Intelligence and Machine Learning",
             details: "Sponsored by Amazon Web Services (AWS)\n\nAmazon Web Services (AWS) has the broadest and deepest set of machine learning and AI services for your business. While machine learning has been around for over 50 years, the cloud is enabling it to be applied at scale. The abundance of data in our daily lives and in business operations is essential for machine learning. In the cloud we can store as much data as we want, cheaply and securely. As a result, AI, using machine learning, is poised to have a profound impact over an increasingly broad canvas of business and technology areas."),
    ListItem(time: "Day 2\n9:00am - 9:45am",
             name: "Free Thinking: Preparing Kids for Success",
             details: "Sponsored by: Synapse\n\nInvesting Today for Tomorrow’s Talent. It is no secret companies are having a difficult time finding tech talent to fill jobs. How can we invest today to ensure there is talent tomorrow? Come and hear from the companies who are activating their brands in STEM community programs to encourage and assist youth to follow traditional and emerging STEM jobs. These brand activations help with marketing, networking and gaining a customer base as well as investing in the future. During this session, we will talk with companies successfully integrating their brands for current marketing benefits with the ability to get an ROI on possible STEM talent in the future. Additionally, we will hear from community organizations on the ground with students and corporations to build a talent pool for tomorrow."),
    ListItem(time: "Day 2\n9:00am - 9:45am",
             name: "How to Leverage LinkedIn to Grow Your Business or Career in 2020",
             details: "Sponsored by: Synapse\n\nMany people know that LinkedIn is the #1 platform for B2B sales and connecting with the right people, but not many people know HOW TO use it. 5 Attendees will win Free LinkedIn profile assessments which they can redeem at the Summit! Deborrah and Justin will take you through the ins and outs of what a fully optimized profile should include and how to increase the number of qualified leads visiting your profile. Deborrah specializes in Linkedin marketing where her strategies have helped clients build high-profit networks and generate over $300 million in revenue and Justin brings his expertise of bringing people to an optimized profile through his content which is viewed over 150,000 times each month. Key takeaways: - How to optimize your LinkedIn profile for sales even if you’re not an expert on LinkedIn - How to create content to increase traffic to your profile. - How entrepreneurs can use intelligence to connect with buyers, investors, and partners."),
    ListItem(time: "Day 2\n9:00am - 9:45am",
             name: "Seizing Success: A Woman's Guide to Transformational Leadership",
             details: "Sponsored by: Synapse\n\nInnovative organizations have transformational leaders that can engage their organization’s culture through a compelling vision, collaboration and spearheading change. They understand their followers’ strengths, communicate clear expectations and provide ongoing coaching. Women are particularly suited to become transformational leaders in whatever they do. In her inspiring, research based talk, Dr. Mary Key will transport you to a place where women can see more clearly leadership options not only available to them but that build on their natural strengths. She shares compelling stories and strategies that will help you get from where you are to where you want to be. The time is right for women to take the lead and go beyond what we have imagined. Our natural strengths lend themselves to be innovative leaders now and in the future."),
    ListItem(time: "Day 2\n9:00am - 9:45am",
             name: "The Secret Sauce: Why the Executive Assistant is the Nerve Center of a Successful Tech Company",
             details: "Sponsored by: Synapse\n\nTech companies are made up of smart people, great ideas and the demand for innovation and agility. To be successful, you need a fast-paced, inclusive culture that can support and sustain growth and constant change. That’s where the role of the Executive Assistant comes in. Beyond the ability to manage the C-level’s crazy schedule, the EA’s job at a tech company is to help facilitate and grow the culture, including getting to know team members and keeping his/her pulse on what’s going on. Learn how EAs from some of the Tampa Bay area’s most respected tech companies serve a truly unique and vital role supporting the powerhouse C-suite."),
    ListItem(time: "Day 2\n9:00am - 9:30am",
             name: "PwC: A Differentiated Employee Experience",
             details: "Sponsored by: PwC\n\nA showcase of how PwC differentiates itself in the marketplace to create a best in class culture and working experience."),
    ListItem(time: "Day 2\n9:00am - 10:00am",
             name: "Driving Innovation: Culture vs Talent with Craig Dawson, PhD",
             details: "Sponsored by: InVista Talent\n\nDo you want innovation to thrive in your organization? There are coachable best practices that generate predictable results. Learn how key innovators think and flourish. Recognize the aspects of culture that create the most fertile grounds for innovative creativity. Find out how the most successful organizations think about innovation and how it’s harnessed. Aligning best-in-class culture strategies beside best-in-class talent management, this presentation will draw from science and practice to arm you with insights into how to make your organization more innovative and ultimately more successful."),
    ListItem(time: "Day 2\n9:30am - 11:30am",
             name: "Coffee + Capital: Accredited Investor Event",
             details: "Sponsored by Florida Funders\n\nThis session will be exclusively for Accredited Investors and will include networking, industry expert discussions, and a unique opportunity to hear from some of Florida's most interesting early-stage companies. You will hear from Florida Funders managing partner Tom Wallace and ReliaQuest CEO Brian Murphy on tech trends in venture capital. To RSVP for the session, please follow the link below and enter your information. All attendees must be Accredited Investors (Accredited Investors as defined by the SEC is an individual that makes more than $200k/year or has assets over $1M). You must pre-register on the Florida Funders investor portal, if you are not registered on our portal, you will not be allowed in the event and will need to complete a step at the door to get in, so please register before hand. RSVP Here: https://www.eventbrite.com/e/coffee-venture-capital-tickets-86923341053"),
    ListItem(time: "Day 2\n9:30am - 10:00am",
             name: "Florida-Israel Business Accelerator (FIBA)- Cohort Company Demos",
             details: "Sponsored by: Synapse\n\nThe Florida-Israel Business Accelerator (FIBA) is a business development program designed to establish and grow successful, high-growth tech ventures in Florida. FIBA connects Israel’s most high-potential tech startups to the partners, investors and advisors they need to launch successfully in the US, specifically, Florida. We recruit tech startups that align with 2 key verticals in Florida, Health Tech and Urban Tech."),


      ListItem(time: "Day 2\n10:00am - 10:45am",
               name: "Business Driven Education: Upskilling Your Workforce for the New Workload",
               details: "Sponsored by: USF Muma College of Business\n\nNo business can reach the top without the right people in place to help it get there. Whether your business is in science, technology, engineering, or mathematics, you need to have the best people in position to support it. But, how do you find them? These experts have insights into how we learn and can prepare ourselves - young and old - for the future."),
      ListItem(time: "Day 2\n10:00am - 10:45am",
               name: "Improving Florida's Energy Ecosystem",
               details: "Sponsored by: TECO\n\nThe energy industry is the foundation for everything innovative. Are you ready to learn about the latest innovations in the industry? This session will highlight the emerging technology in the energy industry. Accompany SaLisa Berrien, Clayton Ferrera, and Tim O'Connor as they discuss the technology that is creating a brighter future for us all."),
      ListItem(time: "Day 2\n10:00am - 10:45am",
               name: "Transforming Healthcare Innovation into Scalable Businesses",
               details: "Sponsored by: AdventHealth\n\nRaising capital for a startup is no easy feat, especially in the healthcare vertical. Learn what it takes to get the investment needed to build, launch, and grow the next great healthcare disruptor."),
      ListItem(time: "Day 2\n10:00am - 10:45am",
               name: "Next-Gen Fan Experiences: Innovation in Sports",
               details: "Sponsored by: Synapse\n\nIn today's Experience Age, all businesses must create a truly remarkable consumer experience; something so unique and valuable that their competition becomes irrelevant. In the business of professional sports, the Fan Experience has become a primary focus. But the competition isn’t just the opposing team—the competition now includes mobile media and high-definition home theaters that make going to a live game less enticing. How can professional sports teams innovate and adopt a true Fan First focus through the use of technology AND real human interaction? And how can other industries incorporate these same strategies to create consumer demand rather than lamenting “empty seats?”"),
      ListItem(time: "Day 2\n10:00am - 10:45am",
               name: "Top Trends in PropTech",
               details: "Sponsored by: Florida-Israel Business Accelerator (FIBA)\n\nAre you interested in the technology that will make a huge impact in urban areas for real estate? This session explores the emerging urban tech that will stimulate the real estate industry. Join us as we discuss how this technology will change the way that we live and connect with one another."),
      ListItem(time: "Day 2\n10:00am - 10:45am",
               name: "Scaling Up: Insights on Leveling Up Your Business",
               details: "Sponsored by: Deloitte\n\nWhether running a startup or a publicly traded giant, every CEO is laser-focused on growing stronger businesses. Learn from four dynamic leaders about how to maintain and scale companies for success in this session hosted by Startup Sisters USA and sponsored by Deloitte. These panelists represent various stages of corporate growth, so no matter if you are new entrepreneur or a seasoned executive, you will walk away with tactical insights to build better businesses."),
      ListItem(time: "Day 2\n10:00am - 11:00am",
               name: "Veteran Talent Hour",
               details: "Sponsored by: Jabil\n\nLooking to network, find your next great hire or great place to work? Join us in the Talent Lounge! For veterans and active duty military, including companies looking to hire veterans."),
      ListItem(time: "Day 2\n10:00am - 10:30am",
               name: "Inclusive Leadership (Diversity and Inclusion)",
               details: "Sponsored by: PwC\n\nA session that will focus on challenging assumptions to build inclusive leaders and create a greater sense of belonging."),
      ListItem(time: "Day 2\n10:00am - 4:00pm",
               name: "VIP Loft - Wednesday",
               details: "VIPs can connect and enjoy complimentary refreshments in this exclusive loft located in the RSM Loft on the 4th floor."),
      ListItem(time: "Day 2\n10:30am - 11:00am",
               name: "Up Close with Arnie Bellini",
               details: "Sponsored by: Synapse"),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "Tech + Talent: Maximize Your Data's Value",
               details: "Sponsored by: Synapse\n\nMost C-Suite level leaders simply haven't been educated on how to maximize their data's value through both systems and people, and many workers outside of the data world are not data literate or simply don't trust the data. Creating this culture takes time and education. Senior leaders who understand the value and potential of their data ask better questions and insist on better, data-informed answers. They insist that their people make data-informed decisions and that their systems provide access to the right data to all levels. And when the right data-driven culture permeates an organization workers at every level insist on access to the right information to make their decisions. Come and learn from a discussion addressing the value of data analytics and also on the importance of talent and culture in transforming an organization into one that properly exploits analytics. It is more than simply “finding the right data scientists and programmers”; we also must create a culture where everyone in the organization has access to the right information to make the best decisions at every level of the organization. Learn why decision-makers must insist on proper evidence to inform their decision- routinely insisting on timely, accurate insights from the organization's data."),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "What NOT to do When Building an App",
               details: "Sponsored by E2 Generations\n\nAnyone can find basic advice on building an app. Tips and tricks on how to make it just right. But, they rarely focus on the bad ideas and past mistakes of previous app-builders. These experts have been in the trenches building products for their own businesses, startups and clients. It’s time to hear what NOT to do, so you can skip the same old mistakes of the past, and find success in building your app."),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "Creative Problem Solving Around Tampa Bay's Transportation Infrastructure",
               details: "Sponsored by: PwC\n\nAn empathetic mindset is the key to identifying and solving the world's most challenging problems. Through our session you will get a hands-on chance to solve a Tampa public issue using the design thinking methodology."),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "Reaching Escape Velocity: Innovation and the New Space Race",
               details: "Sponsored by: Synapse\n\nThe Moon and Mars are calling, and it will take startups, governments, investors, and more to conquer the final frontier. Hear from a panel of space experts, including NASA technology leaders, rocket scientists, and innovators, on how cutting edge, disruptive technologies are the key to future of space."),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "Capitalizing on Innovation: Powering Technology Transfer",
               details: "Sponsored by Enterprise Florida\n\nFlorida innovators in private industries and academia are incredibly prolific, but getting those ideas to market is not always easy. With statewide resources like the Florida High Tech Corridor and Enterprise Florida and national resources like those at the Department of Energy, with 17 national labs and $18 billion in resources, companies have new opportunities propelling them forward. This session will focus on identifying those opportunities and how to take advantage of them to power your innovation."),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "Up Close with ReliaQuest CEO Brian Murphy",
               details: "Sponsored by: ReliaQuest\n\nBrian Murphy is founder and CEO of ReliaQuest, one of the fastest-growing companies in the global cybersecurity industry fortifying the world's most trusted brands against cyber threats. Join us for this Up Close and Personal session with Brian Murphy, named one of the most influential business leaders in Florida, and Tampa Bay Business Journal's Lauren Coffey where they will dive in to Brian's unique approach to driving operational excellence which has led ReliaQuest to receive numerous accolades for its positive company culture and remarkably fast growth."),
      ListItem(time: "Day 2\n11:00am - 11:45am",
               name: "FUN-damentals of SMART Building",
               details: "Sponsored by Strategic Property Partners\n\nThere is a recent proliferation of “smart buildings” spanning everything from single smart homes to entire connected communities. While there is a wide ranging definition of what exactly constitutes smart buildings, it typically includes creating a safer, friendlier, greener, more connected, more automated and more efficient space to live, work or play. But what exactly are the necessary components of a smart development and how are these desired end results best achieved? These experts share the underlying technologies and infrastructure needed to enable the censors, applications and integrated systems characteristic of smart buildings."),
      ListItem(time: "Day 2\n11:00am - 1:30pm",
               name: "Lunch - Wednesday",
               details: "Enjoy your lunch while listening to the capitvating keynote presentations! Take a seat in Sections 123 or 124 on Level 3 to get a front row seat at the mainstage.\n\nGeneral Attendees:\nPlease take advantage of the open design kitchens to purchase lunch. Vegetarian options available.\nEasy Sliders or Steak Station at Section 122 on Level 3\nHavana Nights or Dog Gone-it at Section 109 on Level 3\n\nSponsors, Exhibitors and VIPs\nPickup your complimentary lunch at one of these stations:\nFirestick Grill (near Section 201) on Level 4 or\nTalent Hub on Level 1\n\nCatered lunches are provided by Inside the Box catering, a social enterprise of Metropolitan Ministries. Inside the Box Catering serves delicious food and provides culinary arts education and hands-on vocational training to men and women transitioning out of homelessness."),
      ListItem(time: "Day 2\n12:00pm - 1:30pm",
               name: "Keynote Presentation featuring Sara Blakely, Founder and CEO of SPANX",
               details: "Sponsored by: Synapse\n\nSeating is accessible via Sections 123 + 124 on the Promenade Level"),
      ListItem(time: "Day 2\n2:00pm - 3:00pm",
               name: "Venture Talent Hour",
               details: "Sponsored by SEED Florida Early Stage Investment Fund\n\nFor investors at any stage looking to connect."),
      ListItem(time: "Day 2\n2:00pm - 2:30pm",
               name: "Creative Problem Solving Around Tampa Bay's Water Pollution",
               details: "Sponsored by: PwC\n\nAn empathetic mindset is the key to identifying and solving the world's most challenging problems. Through our session you will get a hands-on chance to solve a Tampa public issue using the design thinking methodology."),
      ListItem(time: "Day 2\n2:00pm - 2:45pm",
               name: "Florida's Appeal: Why Successful Business Leaders are Moving to the Sunshine State",
               details: "Sponsored by: Synapse\n\nSuccessful business leaders are among the nearly 1,000 people moving to Florida every day—leaving places like Silicon Valley and New York for opportunities to lead enterprise companies and establish new ventures. What's bringing them here, and how can we encourage more to follow?"),
      ListItem(time: "Day 2\n2:00pm - 2:45pm",
               name: "High Potential: Florida's Growing Cannabis Industry",
               details: "Sponsored by Cherry Bekaert\n\nThe growing cannabis industry has become a game-changer for Florida. Studies forecast legal marijuana sales in Florida will grow by 6 percent over the next five years - more than $1 billion. This discussion will cover all sides of this fast-growing industry, from government regulation, financial and legal implications and why Florida is uniquely positioned to become a leader in the field."),
      ListItem(time: "Day 2\n2:00pm - 2:45pm",
               name: "The Intersection of Government and Innovation: A Military Perspective",
               details: "Sponsored by Synapse"),
      ListItem(time: "Day 2\n2:00pm - 2:45pm",
               name: "Excuse the Investment",
               details: "Sponsored by Florida Funders\n\nA lively debate between industry experts about hot-button topics within the start-up world."),
      ListItem(time: "Day 2\n2:00pm - 2:45pm",
               name: "From the Production Floor to Artistic Experience: Digital Technology Impacting Life and Art",
               details: "Sponsored by: Jabil\n\nJoin us at The Dali as Scott Gebicke, Head of Global Energy at Jabil,and Hank Hine, Executive Director of the Dali Museum, discusses innovations in Artificial Intelligence (AI), Virtual Reality (VR) and 3-D technology in From the Production Floor to Artistic Experience. Scott, whose work encompasses IoT (the internet of things), will present a sweeping view of how the terrain of our culture alters with the advance of digital technologies. He will examine some of the experiences The Dali has implemented to enhance the understanding of and pleasure in our artworks, as well as digital advances on other fronts. His talk will touch on what promising technological innovations lie ahead, and the potential negative repercussions of constantly evolving tech in our lives."),
      ListItem(time: "Day 2\n2:00pm - 2:45pm",
               name: "Hyperautomation Driving Innovation: Empowering Our Human Resources",
               details: "Sponsored by: A-LIGN\n\nInnovation is the result of successful people, process, and technology changes that enable a new level of productivity and performance. Hyperautomation facilitates both radical and incremental innovations by changing the way humans execute processes, often by design, replacing fractions of the human workforce with that of the digital kind. These new levels of productivity and performance realized by introduction hyper automation is not without cost to the human workforce. More than any other emerging technology, Hyperatomation is met with a stigma which can only be overcome when organizations take steps to facilitate the education of the human workforce on the advantages of introduction the technology. The most innovative organizations will understand the role of upskilling and reallocating human talent as Hyperautomation disrupts the status quo."),
      ListItem(time: "Day 2\n2:30pm - 3:00pm",
               name: "Mayor Jane Castor's Intersection to Innovation: A Call To Action",
               details: "Sponsored by: Synapse\n\nJoin us for Mayor Castor's call to action for Tampa Bay's Innovators! Join City of Tampa Mayor Jane Castor as she announces her newest program Intersection of Innovation- a program which will augment the Mayor’s Transforming Tampa’s Tomorrow initiative by fostering innovation to enhance mobility, workforce development, housing affordability, development and sustainability. The City of Tampa will work with the Innovation Community to make it easier for innovators to engage City departments, understand the Mayor’s vision and deploy projects to address community needs. Mayor Castor will also be announcing some innovative projects that are currently underway within the city."),
      ListItem(time: "Day 2\n2:30pm - 4:30pm",
               name: "Data and Population Health: Community Round Table",
               details: "Sponsored by: Synapse\n\nHealthcare is ripe for disruption. With the role of technology rapidly growing within the healthcare industry, the impact of data is a topic that should be top of mind. Join Florida's best innovators, payers, providers, and more for an open town hall discussion on how technology and data is impacting population health in 2020 and beyond."),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "Florida Early Stage Investing",
               details: "Sponsored by SEED Florida\n\nFlorida is full of exciting innovations and startups that need investors. We will discuss the different types of organizations that actively fund early stage companies as well as the best ways for companies to attract notice of investors."),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "Women in Business Talent Hour",
               details: "Hosted by: StartUp Sisters\n\nLooking to network, find your next great hire or great place to work? Join us in the Talent Lounge! For women at any stage of their professional journey."),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "Exit Strategies: Preparing Your Business for Sale",
               details: "Sponsored by BNY Mellon Wealth Management\n\nMany entrepreneurs dream of a big exit, but few know how to prepare their company for sale, navigate the process smoothly and what to do once you're on the other side. These industry experts have decades of experiences helping founders through this process and will answer your questions so you're ready for the big sell."),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "Pay with Your Face: Preserving User Privacy while Enhancing Convenience",
               details: "Sponsored by: Synapse\n\nIn one of the most cutting-edge sessions, we will examine the emerging tech in smart cities, where people can now pay for items using facial recognition software. This session will answer questions about how this tech preserves privacy, while making purchases at the utmost convenience. Join industry thought leaders as they discuss how facial recognition is changing eCommerce; biometric policy (privacy law, data protection, etc.); technology accuracy; reduced wait times in lines at high-trafficked venues; speed of transactions and more!"),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "A Fireside Chat with Department of Energy Under Secretary Paul Dabbar",
               details: "Sponsored by: Synapse"),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "Innovation Protecting Florida’s Delicate Ecosystem",
               details: "Sponsored by: Synapse\n\nMother Nature is the great innovator. How we maintain and protect her natural habitats, where wildlife can thrive, relies heavily on innovation and technology. Join a panel of biologists, conservationists and Florida ecosystem experts as they share their front line stories and the groundbreaking work they are doing to protect our most valuable resources."),
      ListItem(time: "Day 2\n3:00pm - 3:45pm",
               name: "Practical Uses for AI and IA (Intelligence Augmentation)",
               details: "Sponsored by: Synapse\n\nJoin the conversation about AI (Artificial Intelligence) vs IA (Intelligent Augmentation) Agents and the evolution of IA technology over the last twenty years. Hear about one of the largest commercial applications of military AI technology and how many diverse “AI” technologies, such as NLP, Machine Learning, Heuristic algorithms, etc. come together to deliver real-time applications"),
      ListItem(time: "Day 2\n3:00pm - 3:30pm",
               name: "Creative Problem Solving Around Tampa Bay's Coastal Resiliency",
               details: "Sponsored by: PwC\n\nAn empathetic mindset is the key to identifying and solving the world's most challenging problems. Through our session you will get a hands-on chance to solve a Tampa public issue using the design thinking methodology."),
      ListItem(time: "Day 2\n3:30pm - 4:00pm",
               name: "Up Close with Jeff Vinik",
               details: "Sponsored by: Synapse\n\nA rare opportunity for an intimate discussion with Jeff Vinik, owner of the Tampa Bay Lightning and visionary transforming downtown Tampa."),
      ListItem(time: "Day 2\n4:00pm - 4:45pm",
               name: "Art: the Ultimate Source of Civic & Consumer Engagement",
               details: "Sponsored by: Synapse\n\nWith limitless corporations to choose from, your business needs to stand out from the crowd.  Savvy communicators now understand that art driven initiatives produce deep and authentic emotional experiences which profoundly bind their consumers to the organizations/companies/products they represent.   It is more than what the company can offer, it is how that offer is packaged.  Join us to hear insights on how to create that “wow” factor through innovations in art."),
      ListItem(time: "Day 2\n4:00pm - 4:45pm",
               name: "Invitation Only: Department of Energy Roundtable",
               details: "Sponsored by: Synapse"),
      ListItem(time: "Day 2\n4:00pm - 4:45pm",
               name: "Marketing in 2030",
               details: "Sponsored by: Synapse\n\nIn a world of exciting technology and online interactions, it is important to not forget that there are more ways to market outside of popular platforms such as social media. Social media has become the new norm for marketing, branding and building a community. Although, it is a great tool, it is not the only one. There are other ways to create a community. In this session, Alina Alvarez, Loran Jarrett, Wendy Culpepper, Kelly Wilson, and Zach Gresham will teach you to think outside the box (or phone) and create a strong network of people that can interact and help each other."),
      ListItem(time: "Day 2\n4:00pm - 4:45pm",
               name: "Architect Your Tech for Scale and Sale: Building Investible Technology That Scales With Growth",
               details: "Sponsored by: Florida Funders\n\nFlorida Funders and Haneke Design have partnered together to share their professional experiences around industry best practices in software development as well as key items to look for when evaluating attractive technology for investors. Understanding technical best practices and leveraging them to build investable grade technology is critical for building successful scalable applications that yield a return for investors."),
      ListItem(time: "Day 2\n4:00pm - 4:45pm",
               name: "Tapping In To Gen-Z: The Largest Generation in American History",
               details: "Sponsored by: Synapse\n\nGen Z consumers grew up with technology, the internet and social media. Now they are finishing college and entering the workforce. Gen Z'ers are soon to become the largest consumer cohort and one of the most powerful consumer forces in the market today. But how do we get our message to them? With each new generation, our forms of communication must evolve. Learn how Spectrum Reach's Kernel Creative Strategies can assist by connecting you with the largest generation in American history."),
      ListItem(time: "Day 2\n4:00pm - 4:30pm",
               name: "Creative Problem Solving Around Networking with Fellow Tampa Tech Professionals",
               details: "Sponsored by: PwC\n\nAn empathetic mindset is the key to identifying and solving the world's most challenging problems. Through our session you will get a hands-on chance to solve a Tampa public issue using the design thinking methodology."),
      ListItem(time: "Day 2\n4:00pm - 5:30pm",
               name: "Happy Hour Hosted by InVista Talent",
               details: "Sponsored by: InVista Talent"),
      ListItem(time: "Day 2\n4:30pm - 5:00pm",
               name: "Pitch Madness - Final Face Off",
               details: "In a world that preaches disruption, founders have been stuck pitching their startups through the same boring format for way too long. So we set out to develop a better way for entrepreneurs to put their talents on display as visionaries and company builders.​Pitch Madness combines the elements of a Head2Head tournament with monitored debate, creating an environment where founders have to think on their feet!"),
      ListItem(time: "Day 2\n5:00pm - 7:00pm",
               name: "Embarc Collective Official Launch Event",
               details: "Tour Embarc Collective’s state-of-the-art 32,000 square-foot collaboration facility and enjoy light bites and drinks by Endeavr Embarc Collective - 802 E. Whiting Street, Tampa Click here to RVSP: https://launchatec.splashthat.com/"),
      ListItem(time: "Day 2\n5:30pm - 8:00pm",
               name: "Synapse Social- Day 2 After-Party: Night Out at Sparkman Wharf",
               details: "Sparkman Wharf is located in the Channelside Bay Plaza at 615 Channelside Dr, Tampa, FL 33602\n\nKeep the party going at Tampa's hottest outdoor venue. Eat, drink, play and keep the connections going all night. Sparkman Wharf is a quick walk down Channelside Drive from the Amalie Arena."),
  ]

  var body: some View {
    List {
      ForEach(items.indices) { index in
        NavigationLink(destination: DetailView(item: self.items[index])) {
          VStack(alignment: .leading) {
            Text(self.items[index].time).foregroundColor(.blue)
            Text(self.items[index].name).fontWeight(.bold)
          }.padding(10)
        }.listRowBackground((index  % 2 == 0) ? Color(.black) : self.gray)
      }
    }
  }

}
